import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

// Template
// 여러 페이지 간에 공유되는 UI
// 레이아웃과 달리 템플릿은 탐색마다 새로운 인스턴스 사용
// 특별한 이유가 없다면 템플릿 대신에 레이아웃 사용을 권장

// Layout
// 여러 페이지 간에 공유되는 UI
// 상태를 유지하여 리렌더링이 되지 않음
// 페이지를 감싸며, 레이아웃끼리 중첩하여 사용 가능(child props 활용)

// RootLayout
// src/app/layout.tsx
// 최상위 레이아웃으로 모든 페이지에서 공유
// 루트 레이아웃에서만 <html>, <body> 태그를 포함
// RootLayout -> OtherPageLayout -> OtherPage -> ...
export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
